//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Answer = new HashSet<Answer>();
        }
    
        public int StuID { get; set; }
       // [Required(ErrorMessage = "姓名是必填项")]
        public string StuName { get; set; }
        [Required(ErrorMessage = "登录名是必填项")]
        public string StuLoginName { get; set; }
        [Required(ErrorMessage = "密码是必填项")]
        public string StuLoginPwd { get; set; }
        public bool StuSex { get; set; }
        public string StuPhone { get; set; }
        public string StuEmail { get; set; }
        public string StuGrade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answer { get; set; }
    }
}
